name: Nix CI workflow
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      if: false # To be enabled on each downstream (from template) repository.
      with:
        name: ${{ env.CACHIX_REPO_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix flake check --print-build-logs

  shell:
    runs-on: ubuntu-latest
    if: false # To be enabled on each downstream (from template) repository.
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: ${{ env.CACHIX_REPO_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix build .#devShells.x86_64-linux.default --print-build-logs

  wsl2-linux-kernel:
    runs-on: ubuntu-latest
    if: false # To be enabled on each downstream (from template) repository.
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: ${{ env.CACHIX_REPO_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix build .#packages.x86_64-linux.wsl2-linux-kernel --print-build-logs
