name: "Nix build"
on:
  pull_request:
  push:
env:
  CACHIX_REPO_NAME: "wsl2-linux-kernel-package-template"
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V28
    - uses: cachix/cachix-action@v15
      if: false
      with:
        name: ${{ env.CACHIX_REPO_NAME }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check --print-build-logs

  shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V28
    - uses: cachix/cachix-action@v15
      if: false
      with:
        name: ${{ env.CACHIX_REPO_NAME }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#devShells.x86_64-linux.default --print-build-logs
    - run: nix build .#packages.x86_64-linux.wsl2-linux-kernel --print-build-logs
